"""empty message

Revision ID: 8f964cd1f0e5
Revises: 
Create Date: 2022-07-24 12:53:29.282164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f964cd1f0e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('extra_costs', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'percentage')
    op.drop_column('products', 'extra_costs')
    op.drop_column('products', 'purchase_price')
    # ### end Alembic commands ###
